package hbm.model;
// Generated 2021-6-19 21:40:48 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Callouttask generated by hbm2java
 */
public class Callouttask implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -233514485798671902L;
	private String id;
	private String name;
	private Date startdate;
	private Date expiredate;
	private String trunkid;
	private String workdeptid;
	private int period;
	private String batchid;
	private int status;
	private int executions;
	private int finishes;
	private Date nextdate;
	private double agentratio;

	public Callouttask() {
	}

	public Callouttask(String id, String name, Date startdate, Date expiredate, String trunkid, String workdeptid,int period,
			String batchid, int status, int executions, int finishes, Date nextdate, double agentratio) {
		this.id = id;
		this.name = name;
		this.startdate = startdate;
		this.expiredate = expiredate;
		this.trunkid = trunkid;
		this.workdeptid = workdeptid;
		this.period = period;
		this.batchid = batchid;
		this.status = status;
		this.executions = executions;
		this.finishes = finishes;
		this.nextdate = nextdate;
		this.agentratio = agentratio;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	public Date getExpiredate() {
		return this.expiredate;
	}

	public void setExpiredate(Date expiredate) {
		this.expiredate = expiredate;
	}

	public String getTrunkid() {
		return this.trunkid;
	}

	public void setTrunkid(String trunkid) {
		this.trunkid = trunkid;
	}
	
	public String getWorkdeptid() {
		return this.workdeptid;
	}

	public void setWorkdeptid(String workdeptid) {
		this.workdeptid = workdeptid;
	}
	
	public int getPeriod() {
		return this.period;
	}

	public void setPeriod(int period) {
		this.period = period;
	}

	public String getBatchid() {
		return this.batchid;
	}

	public void setBatchid(String batchid) {
		this.batchid = batchid;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getExecutions() {
		return this.executions;
	}

	public void setExecutions(int executions) {
		this.executions = executions;
	}

	public int getFinishes() {
		return this.finishes;
	}

	public void setFinishes(int finishes) {
		this.finishes = finishes;
	}

	public Date getNextdate() {
		return this.nextdate;
	}

	public void setNextdate(Date nextdate) {
		this.nextdate = nextdate;
	}

	public double getAgentratio() {
		return this.agentratio;
	}

	public void setAgentratio(double agentratio) {
		this.agentratio = agentratio;
	}

}
