package hbm.model;
// Generated 2019-5-28 9:28:15 by Hibernate Tools 4.3.5.Final

/**
 * Calloutphone generated by hbm2java
 */
public class Calloutphone implements java.io.Serializable {

	private static final long serialVersionUID = 9090057367093353238L;
	private CalloutphoneId id;
	private int taskorder;

	public Calloutphone() {
	}

	public Calloutphone(CalloutphoneId id, int taskorder) {
		this.id = id;
		this.taskorder = taskorder;
	}

	public CalloutphoneId getId() {
		return this.id;
	}

	public void setId(CalloutphoneId id) {
		this.id = id;
	}

	public int getTaskorder() {
		return this.taskorder;
	}

	public void setTaskorder(int taskorder) {
		this.taskorder = taskorder;
	}

}
