package hbm.model;
// Generated 2019-5-24 15:31:52 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Callouttrunk generated by hbm2java
 */
public class Callouttrunk implements java.io.Serializable {

	private static final long serialVersionUID = 2537715864836750343L;
	private String id;
	private String name;
	private String trunk;
	private int intercurrent;
	private int delay;
	private Date createdate;
	private Date updatedate;
	private int status;
	private int maxretrycount;
	private int timetolive;
	

	public Callouttrunk() {
	}

	public Callouttrunk(String id, String name, String trunk, int intercurrent, int delay, Date createdate,
			Date updatedate, int status, int maxretrycount,int timetolive) {
		this.id = id;
		this.name = name;
		this.trunk = trunk;
		this.intercurrent = intercurrent;
		this.delay = delay;
		this.createdate = createdate;
		this.updatedate = updatedate;
		this.status = status;
		this.maxretrycount = maxretrycount;
		this.timetolive = timetolive;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTrunk() {
		return this.trunk;
	}

	public void setTrunk(String trunk) {
		this.trunk = trunk;
	}

	public int getIntercurrent() {
		return this.intercurrent;
	}

	public void setIntercurrent(int intercurrent) {
		this.intercurrent = intercurrent;
	}

	public int getDelay() {
		return this.delay;
	}

	public void setDelay(int delay) {
		this.delay = delay;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getMaxretrycount() {
		return this.maxretrycount;
	}

	public void setMaxretrycount(int maxretrycount) {
		this.maxretrycount = maxretrycount;
	}

	public int getTimetolive() {
		return timetolive;
	}

	public void setTimetolive(int timetolive) {
		this.timetolive = timetolive;
	}
}
