package hbm.model;
// Generated 2019-5-31 17:46:49 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Calloutrecord generated by hbm2java
 */

public class Calloutrecord implements java.io.Serializable {

	private static final long serialVersionUID = 7511162040590162534L;
	private String id;
	private String taskid;
	private String phone;
	private int status;
	private String calluuid;
	private int retrycount;
	private int completestatus;
	private Date completedate;
	private String results;
	private int taskorder;
	private int executions;
	private int talklength;

	public Calloutrecord() {
	}

	public Calloutrecord(String id, String taskid, String phone, int status, String calluuid, int retrycount,
			int completestatus, Date completedate, String results, int taskorder, int executions, int talklength) {
		this.id = id;
		this.taskid = taskid;
		this.phone = phone;
		this.status = status;
		this.calluuid = calluuid;
		this.retrycount = retrycount;
		this.completestatus = completestatus;
		this.completedate = completedate;
		this.results = results;
		this.taskorder = taskorder;
		this.executions = executions;
		this.talklength = talklength;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTaskid() {
		return this.taskid;
	}

	public void setTaskid(String taskid) {
		this.taskid = taskid;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public String getCalluuid() {
		return this.calluuid;
	}

	public void setCalluuid(String calluuid) {
		this.calluuid = calluuid;
	}

	public int getRetrycount() {
		return this.retrycount;
	}

	public void setRetrycount(int retrycount) {
		this.retrycount = retrycount;
	}

	public int getCompletestatus() {
		return this.completestatus;
	}

	public void setCompletestatus(int completestatus) {
		this.completestatus = completestatus;
	}

	public Date getCompletedate() {
		return this.completedate;
	}

	public void setCompletedate(Date completedate) {
		this.completedate = completedate;
	}

	public String getResults() {
		return this.results;
	}

	public void setResults(String results) {
		this.results = results;
	}

	public int getTaskorder() {
		return this.taskorder;
	}

	public void setTaskorder(int taskorder) {
		this.taskorder = taskorder;
	}

	public int getExecutions() {
		return this.executions;
	}

	public void setExecutions(int executions) {
		this.executions = executions;
	}

	public int getTalklength() {
		return this.talklength;
	}

	public void setTalklength(int talklength) {
		this.talklength = talklength;
	}

}
