package hbm.model;
// Generated 2018-7-3 16:07:43 by Hibernate Tools 4.0.1.Final

/**
 * Rbacroleoperation generated by hbm2java
 */
public class Rbacroleoperation implements java.io.Serializable {

	private RbacroleoperationId id;

	public Rbacroleoperation() {
	}

	public Rbacroleoperation(RbacroleoperationId id) {
		this.id = id;
	}

	public RbacroleoperationId getId() {
		return this.id;
	}

	public void setId(RbacroleoperationId id) {
		this.id = id;
	}

}
