package hbm.model;
// Generated 2018-7-3 16:07:43 by Hibernate Tools 4.0.1.Final

/**
 * Rbacuser generated by hbm2java
 */
public class Rbacuser implements java.io.Serializable {

	private String userguid;
	private String nickname;
	private String headimgurl;

	public Rbacuser() {
	}

	public Rbacuser(String userguid, String nickname, String headimgurl) {
		this.userguid = userguid;
		this.nickname = nickname;
		this.headimgurl = headimgurl;
	}

	public String getUserguid() {
		return this.userguid;
	}

	public void setUserguid(String userguid) {
		this.userguid = userguid;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getHeadimgurl() {
		return this.headimgurl;
	}

	public void setHeadimgurl(String headimgurl) {
		this.headimgurl = headimgurl;
	}

}
