package hbm.model;
// Generated 2018-9-18 10:35:48 by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * Rbactoken generated by hbm2java
 */
public class Rbactoken implements java.io.Serializable {

	private String id;
	private String roleguid;
	private Date expiresdate;
	private Date createdate;
	private String code;

	public Rbactoken() {
	}

	public Rbactoken(String id, String roleguid, Date expiresdate, Date createdate, String code) {
		this.id = id;
		this.roleguid = roleguid;
		this.expiresdate = expiresdate;
		this.createdate = createdate;
		this.code = code;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getRoleguid() {
		return this.roleguid;
	}

	public void setRoleguid(String roleguid) {
		this.roleguid = roleguid;
	}

	public Date getExpiresdate() {
		return this.expiresdate;
	}

	public void setExpiresdate(Date expiresdate) {
		this.expiresdate = expiresdate;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
