package hbm.model;
// Generated 2018-7-3 16:07:43 by Hibernate Tools 4.0.1.Final

/**
 * RbacroleuserId generated by hbm2java
 */
public class RbacroleuserId implements java.io.Serializable {

	private String roleguid;
	private String userguid;

	public RbacroleuserId() {
	}

	public RbacroleuserId(String roleguid, String userguid) {
		this.roleguid = roleguid;
		this.userguid = userguid;
	}

	public String getRoleguid() {
		return this.roleguid;
	}

	public void setRoleguid(String roleguid) {
		this.roleguid = roleguid;
	}

	public String getUserguid() {
		return this.userguid;
	}

	public void setUserguid(String userguid) {
		this.userguid = userguid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RbacroleuserId))
			return false;
		RbacroleuserId castOther = (RbacroleuserId) other;

		return ((this.getRoleguid() == castOther.getRoleguid()) || (this.getRoleguid() != null
				&& castOther.getRoleguid() != null && this.getRoleguid().equals(castOther.getRoleguid())))
				&& ((this.getUserguid() == castOther.getUserguid()) || (this.getUserguid() != null
						&& castOther.getUserguid() != null && this.getUserguid().equals(castOther.getUserguid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRoleguid() == null ? 0 : this.getRoleguid().hashCode());
		result = 37 * result + (getUserguid() == null ? 0 : this.getUserguid().hashCode());
		return result;
	}

}
