package hbm.model;
// Generated 2021-10-30 15:02:44 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Rbacauditlog generated by hbm2java
 */
public class Rbacauditlog implements java.io.Serializable {

	private String id;
	private String resourcename;
	private String resourceid;
	private String userguid;
	private Date updatetime;
	private String operationname;
	private int operationstatus;
	private String operationvalue;

	public Rbacauditlog() {
	}

	public Rbacauditlog(String id, String resourcename, String resourceid, String userguid, Date updatetime,
			String operationname, int operationstatus) {
		this.id = id;
		this.resourcename = resourcename;
		this.resourceid = resourceid;
		this.userguid = userguid;
		this.updatetime = updatetime;
		this.operationname = operationname;
		this.operationstatus = operationstatus;
	}

	public Rbacauditlog(String id, String resourcename, String resourceid, String userguid, Date updatetime,
			String operationname, int operationstatus, String operationvalue) {
		this.id = id;
		this.resourcename = resourcename;
		this.resourceid = resourceid;
		this.userguid = userguid;
		this.updatetime = updatetime;
		this.operationname = operationname;
		this.operationstatus = operationstatus;
		this.operationvalue = operationvalue;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getResourcename() {
		return this.resourcename;
	}

	public void setResourcename(String resourcename) {
		this.resourcename = resourcename;
	}

	public String getResourceid() {
		return this.resourceid;
	}

	public void setResourceid(String resourceid) {
		this.resourceid = resourceid;
	}

	public String getUserguid() {
		return this.userguid;
	}

	public void setUserguid(String userguid) {
		this.userguid = userguid;
	}

	public Date getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	public String getOperationname() {
		return this.operationname;
	}

	public void setOperationname(String operationname) {
		this.operationname = operationname;
	}

	public int getOperationstatus() {
		return this.operationstatus;
	}

	public void setOperationstatus(int operationstatus) {
		this.operationstatus = operationstatus;
	}

	public String getOperationvalue() {
		return this.operationvalue;
	}

	public void setOperationvalue(String operationvalue) {
		this.operationvalue = operationvalue;
	}

}
