package hbm.model;
// Generated 2018-7-3 16:07:43 by Hibernate Tools 4.0.1.Final

/**
 * Rbacoperation generated by hbm2java
 */
public class Rbacoperation implements java.io.Serializable {

	private String operationguid;
	private String operationname;

	public Rbacoperation() {
	}

	public Rbacoperation(String operationguid, String operationname) {
		this.operationguid = operationguid;
		this.operationname = operationname;
	}

	public String getOperationguid() {
		return this.operationguid;
	}

	public void setOperationguid(String operationguid) {
		this.operationguid = operationguid;
	}

	public String getOperationname() {
		return this.operationname;
	}

	public void setOperationname(String operationname) {
		this.operationname = operationname;
	}

}
