package hbm.model;
// Generated 2018-7-3 16:07:43 by Hibernate Tools 4.0.1.Final

/**
 * RbacroleoperationId generated by hbm2java
 */
public class RbacroleoperationId implements java.io.Serializable {

	private String roleguid;
	private String operationguid;

	public RbacroleoperationId() {
	}

	public RbacroleoperationId(String roleguid, String operationguid) {
		this.roleguid = roleguid;
		this.operationguid = operationguid;
	}

	public String getRoleguid() {
		return this.roleguid;
	}

	public void setRoleguid(String roleguid) {
		this.roleguid = roleguid;
	}

	public String getOperationguid() {
		return this.operationguid;
	}

	public void setOperationguid(String operationguid) {
		this.operationguid = operationguid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RbacroleoperationId))
			return false;
		RbacroleoperationId castOther = (RbacroleoperationId) other;

		return ((this.getRoleguid() == castOther.getRoleguid()) || (this.getRoleguid() != null
				&& castOther.getRoleguid() != null && this.getRoleguid().equals(castOther.getRoleguid())))
				&& ((this.getOperationguid() == castOther.getOperationguid())
						|| (this.getOperationguid() != null && castOther.getOperationguid() != null
								&& this.getOperationguid().equals(castOther.getOperationguid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRoleguid() == null ? 0 : this.getRoleguid().hashCode());
		result = 37 * result + (getOperationguid() == null ? 0 : this.getOperationguid().hashCode());
		return result;
	}

}
