package hbm.model;
// Generated 2018-9-18 13:24:26 by Hibernate Tools 4.0.1.Final

import java.util.Date;

/**
 * Rbacroleinfo generated by hbm2java
 */
public class Rbacroleinfo implements java.io.Serializable {

	private String roleguid;
	private String secret;
	private Date createdate;
	private Date updatedate;
	private String redirecturi;

	public Rbacroleinfo() {
	}

	public Rbacroleinfo(String roleguid, String secret, Date createdate, Date updatedate, String redirecturi) {
		this.roleguid = roleguid;
		this.secret = secret;
		this.createdate = createdate;
		this.updatedate = updatedate;
		this.redirecturi = redirecturi;
	}

	public String getRoleguid() {
		return this.roleguid;
	}

	public void setRoleguid(String roleguid) {
		this.roleguid = roleguid;
	}

	public String getSecret() {
		return this.secret;
	}

	public void setSecret(String secret) {
		this.secret = secret;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	public String getRedirecturi() {
		return this.redirecturi;
	}

	public void setRedirecturi(String redirecturi) {
		this.redirecturi = redirecturi;
	}

}
