package hbm.model;
// Generated 2019-1-22 14:22:31 by Hibernate Tools 4.3.5.Final

/**
 * Rbacrole generated by hbm2java
 */
public class Rbacrole implements java.io.Serializable {

	private String roleguid;
	private String fatherroleguid;
	private String rolename;
	private int inheritance;

	public Rbacrole() {
	}

	public Rbacrole(String roleguid, String fatherroleguid, String rolename, int inheritance) {
		this.roleguid = roleguid;
		this.fatherroleguid = fatherroleguid;
		this.rolename = rolename;
		this.inheritance = inheritance;
	}

	public String getRoleguid() {
		return this.roleguid;
	}

	public void setRoleguid(String roleguid) {
		this.roleguid = roleguid;
	}

	public String getFatherroleguid() {
		return this.fatherroleguid;
	}

	public void setFatherroleguid(String fatherroleguid) {
		this.fatherroleguid = fatherroleguid;
	}

	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	public int getInheritance() {
		return this.inheritance;
	}

	public void setInheritance(int inheritance) {
		this.inheritance = inheritance;
	}
	
}
