package hbm.model;
// Generated 2018-7-3 16:07:43 by Hibernate Tools 4.0.1.Final

/**
 * Rbacroleuser generated by hbm2java
 */
public class Rbacroleuser implements java.io.Serializable {

	private RbacroleuserId id;

	public Rbacroleuser() {
	}

	public Rbacroleuser(RbacroleuserId id) {
		this.id = id;
	}

	public RbacroleuserId getId() {
		return this.id;
	}

	public void setId(RbacroleuserId id) {
		this.id = id;
	}

}
