package hbm.model;
// Generated 2021-2-3 16:55:54 by Hibernate Tools 4.3.5.Final

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ReccontentId generated by hbm2java
 */
public class ReccontentId implements java.io.Serializable {

	private String id;
	private int channel;
	@JsonProperty(value="start") private int filestart;
	@JsonProperty(value="end") private int fileend;

	public ReccontentId() {
	}

	public ReccontentId(String id, int channel, int filestart, int fileend) {
		this.id = id;
		this.channel = channel;
		this.filestart = filestart;
		this.fileend = fileend;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public int getChannel() {
		return this.channel;
	}

	public void setChannel(int channel) {
		this.channel = channel;
	}

	public int getFilestart() {
		return this.filestart;
	}

	public void setFilestart(int filestart) {
		this.filestart = filestart;
	}

	public int getFileend() {
		return this.fileend;
	}

	public void setFileend(int fileend) {
		this.fileend = fileend;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReccontentId))
			return false;
		ReccontentId castOther = (ReccontentId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& (this.getChannel() == castOther.getChannel()) && (this.getFilestart() == castOther.getFilestart())
				&& (this.getFileend() == castOther.getFileend());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + this.getChannel();
		result = 37 * result + this.getFilestart();
		result = 37 * result + this.getFileend();
		return result;
	}

}
