package hbm.model;
// Generated 2021-2-3 16:55:54 by Hibernate Tools 4.3.5.Final

/**
 * Reccontent generated by hbm2java
 */
public class Reccontent implements java.io.Serializable {

	private ReccontentId id;
	private String audiocontent;
	private long starttime;

	public Reccontent() {
	}

	public Reccontent(ReccontentId id, String audiocontent, long starttime) {
		this.id = id;
		this.audiocontent = audiocontent;
		this.starttime = starttime;
	}

	public ReccontentId getId() {
		return this.id;
	}

	public void setId(ReccontentId id) {
		this.id = id;
	}

	public String getAudiocontent() {
		return this.audiocontent;
	}

	public void setAudiocontent(String audiocontent) {
		this.audiocontent = audiocontent;
	}

	public long getStarttime() {
		return this.starttime;
	}

	public void setStarttime(long starttime) {
		this.starttime = starttime;
	}

}
