package hbm.model;
// Generated 2018-7-15 15:11:51 by Hibernate Tools 4.0.1.Final

/**
 * Recextension generated by hbm2java
 */
public class Recextension implements java.io.Serializable {

	private String extension;
	private String roleguid;

	public Recextension() {
	}

	public Recextension(String extension, String roleguid) {
		this.extension = extension;
		this.roleguid = roleguid;
	}

	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public String getRoleguid() {
		return this.roleguid;
	}

	public void setRoleguid(String roleguid) {
		this.roleguid = roleguid;
	}

}
