package hbm.model;
// Generated 2021-1-22 21:30:54 by Hibernate Tools 4.3.5.Final

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Recphone generated by hbm2java
 */
public class Recphone implements java.io.Serializable {

	@JsonIgnore private String guidid;
	private short host;
	private short channel;
	private short direction;
	private String caller;
	private String called;
	@JsonIgnore private String dialup;
	@JsonIgnore private Date systemtim;
	private long seconds;
	private String extension;
	@JsonIgnore private long ipaddress;
	private String agent;
	@JsonIgnore private long holdseconds;
	@JsonIgnore private short ringseconds;
	@JsonIgnore private short holdcount;
	@JsonIgnore private short connectedcount;
	private String filename;
	private short states;
	private String userdata;
	private String ucid;
	@JsonIgnore private long callid;
	private String roleid;
	private String id;
	private Date createdate;

	public Recphone() {
	}

	public Recphone(String guidid, short host, short channel, short direction, Date systemtim, long seconds,
			long ipaddress, long holdseconds, short ringseconds, short holdcount, short connectedcount, short states,
			String userdata, String ucid, long callid, String roleid, String id, Date createdate) {
		this.guidid = guidid;
		this.host = host;
		this.channel = channel;
		this.direction = direction;
		this.systemtim = systemtim;
		this.seconds = seconds;
		this.ipaddress = ipaddress;
		this.holdseconds = holdseconds;
		this.ringseconds = ringseconds;
		this.holdcount = holdcount;
		this.connectedcount = connectedcount;
		this.states = states;
		this.userdata = userdata;
		this.ucid = ucid;
		this.callid = callid;
		this.roleid = roleid;
		this.id = id;
		this.createdate = createdate;
	}

	public Recphone(String guidid, short host, short channel, short direction, String caller, String called,
			String dialup, Date systemtim, long seconds, String extension, long ipaddress, String agent,
			long holdseconds, short ringseconds, short holdcount, short connectedcount, String filename, short states,
			String userdata, String ucid, long callid, String roleid, String id, Date createdate) {
		this.guidid = guidid;
		this.host = host;
		this.channel = channel;
		this.direction = direction;
		this.caller = caller;
		this.called = called;
		this.dialup = dialup;
		this.systemtim = systemtim;
		this.seconds = seconds;
		this.extension = extension;
		this.ipaddress = ipaddress;
		this.agent = agent;
		this.holdseconds = holdseconds;
		this.ringseconds = ringseconds;
		this.holdcount = holdcount;
		this.connectedcount = connectedcount;
		this.filename = filename;
		this.states = states;
		this.userdata = userdata;
		this.ucid = ucid;
		this.callid = callid;
		this.roleid = roleid;
		this.id = id;
		this.createdate = createdate;
	}

	public String getGuidid() {
		return this.guidid;
	}

	public void setGuidid(String guidid) {
		this.guidid = guidid;
	}

	public short getHost() {
		return this.host;
	}

	public void setHost(short host) {
		this.host = host;
	}

	public short getChannel() {
		return this.channel;
	}

	public void setChannel(short channel) {
		this.channel = channel;
	}

	public short getDirection() {
		return this.direction;
	}

	public void setDirection(short direction) {
		this.direction = direction;
	}

	public String getCaller() {
		return this.caller;
	}

	public void setCaller(String caller) {
		this.caller = caller;
	}

	public String getCalled() {
		return this.called;
	}

	public void setCalled(String called) {
		this.called = called;
	}

	public String getDialup() {
		return this.dialup;
	}

	public void setDialup(String dialup) {
		this.dialup = dialup;
	}

	public Date getSystemtim() {
		return this.systemtim;
	}

	public void setSystemtim(Date systemtim) {
		this.systemtim = systemtim;
	}

	public long getSeconds() {
		return this.seconds;
	}

	public void setSeconds(long seconds) {
		this.seconds = seconds;
	}

	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public long getIpaddress() {
		return this.ipaddress;
	}

	public void setIpaddress(long ipaddress) {
		this.ipaddress = ipaddress;
	}

	public String getAgent() {
		return this.agent;
	}

	public void setAgent(String agent) {
		this.agent = agent;
	}

	public long getHoldseconds() {
		return this.holdseconds;
	}

	public void setHoldseconds(long holdseconds) {
		this.holdseconds = holdseconds;
	}

	public short getRingseconds() {
		return this.ringseconds;
	}

	public void setRingseconds(short ringseconds) {
		this.ringseconds = ringseconds;
	}

	public short getHoldcount() {
		return this.holdcount;
	}

	public void setHoldcount(short holdcount) {
		this.holdcount = holdcount;
	}

	public short getConnectedcount() {
		return this.connectedcount;
	}

	public void setConnectedcount(short connectedcount) {
		this.connectedcount = connectedcount;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public short getStates() {
		return this.states;
	}

	public void setStates(short states) {
		this.states = states;
	}

	public String getUserdata() {
		return this.userdata;
	}

	public void setUserdata(String userdata) {
		this.userdata = userdata;
	}

	public String getUcid() {
		return this.ucid;
	}

	public void setUcid(String ucid) {
		this.ucid = ucid;
	}

	public long getCallid() {
		return this.callid;
	}

	public void setCallid(long callid) {
		this.callid = callid;
	}

	public String getRoleid() {
		return this.roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

}
